name: my first-action

on: push

jobs:
    first-job : 
        runs-on: ubuntu-latest
        steps:
          - name : checkout-action
            uses: actions/checkout@v4.2.2

          - name: Install cowsay
            run: |
                sudo apt update
                sudo apt-get install cowsay -y
                mkdir -p ~/.cows
                curl -o ~/.cows/dragon.cow https://raw.githubusercontent.com/paulkaefer/cowsay-files/master/dragon.cow
                
          - name : Execute
            run: cowsay -f  dragon " I am king " >> dragon.txt

          - name : Read file
            run: cat dragon.txt
