name: job concurrency

on:
  workflow_dispatch:

concurrency:
      group: Run
      cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          sudo apt update
          sudo apt install -y python3

  runner:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run command
        run: |
          python pyramid.py
          
