name: my first-action

on: push

jobs:
    first-job : 
        runs-on: ubuntu-latest
        steps:
          - name : checkout-action
            uses: actions/checkout@v4.2.2
            
          - name: Greetings
            run: |
                echo "hi"
                ls -lrt
                cat README.md

          - name : Third party library
            run : cowsay -f lion "King of jungle" >> lion.txt # -f is used to specify the name
                                                              # cowsay is a third party library

         



    
