name: my first-action

on: push

jobs:
    first-job : 
        runs-on: ubuntu-latest
        steps:
          - name : checkout-action
            uses: checkout@v4
            
          - name: Greetings
            run: echo "hi"

          - name: Listfiles
            run: ls


    
