name: To install and run py file

on : 
    push:
        

jobs:
    build:
        name: VM
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 
            - name: Install python
              run: |
                   sudo apt-get update
                   sudo apt-get install -y python3
            - name: Run program
              run: python pyramid.py



