name: Docker Matrix with Include/Exclude

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [alpine, debian, ubuntu]
        app-version: [v1, v2]

        exclude:
          
          - base-image: alpine
            app-version: v2

        include:
         
          - base-image: busybox
            app-version: v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "Building with base: ${{ matrix.base-image }} and version: ${{ matrix.app-version }}"
          docker build \
            --build-arg BASE_IMAGE=${{ matrix.base-image }} \
            --build-arg APP_VERSION=${{ matrix.app-version }} \
            -t myapp:${{ matrix.base-image }}-${{ matrix.app-version }} .
