name : Matrix

on:
  push

jobs:
  build:
    strategy:
      fail-fast: false
      max-paralell: 2
      matrix:
        os: [ubuntu-latest , windows-latest]
        images: [hello-world , nginx ]
        exclude :
          os: windows-latest
          images: nginx
        include:
          os: ubuntu-22.04
          images: busybox

    runs-on: ${{ matrix.os }}
    steps :
      - uses : actions/checkout@v4

      - name: docker
        run : docker info

      - name : run docker on ${{ matrix.os }}
        run : docker run ${{ matrix.images }}




        - uses: actions/checkout@v4

        
        
