name: Build-Test-Deploy Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Build step
        run: echo "Building the project..." && cowsay "Build complete!"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Test step
        run: echo "Running tests..." && cowsay "Tests passed!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Deploy step
        run: echo "Deploying application..." && cowsay "Deployment successful!"
