name: scripts

on:
  push:

jobs:
    build:
         name: VM
         runs-on: ubuntu-latest
         steps:
           - name: VM
             uses: actions/checkout@v4
       
             run: |
               chmod +x script.sh
               ./script.sh
       
       
     
