name: Secrets

on: [push , issues]

jobs:
  login:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}  

    steps:
      - name: Show username from variable
        run: echo "Logged in as $USERNAME"

      - name: Use secret (do not print)
        run: echo "Using secret password for login"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
