name: Sequence jobs

on:
  issues:
    

jobs:
  build:
    name: VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

  test:
    name: Run Pyramid Script
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run and Install
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          python3 pyramid.py
