name: Upload and download

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Create cowsay output
        run: cowsay -f dragon "Dino" >> sound.txt

      - name: Upload sound.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: sound.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Display structure of downloaded files
        run: ls -R
