name: Upload and download artifacts

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python and Run Script
        run: |
          sudo apt update
          sudo apt install -y python3
          python3 pyramid.py >> output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Display structure of downloaded file
        run: ls -R
