name: variables 

on:
  push:

env:
 DOCKER_REGISTRY: docker.io
 DOCKER_USERNAME: prajnashetty529
 DOCKER_PASSWORD: nageshk@devtools.in

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars. DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  

        
      
  
  
